# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/debian-8.5"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "debian-8.5"
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "debian"
  config.vm.network :private_network, ip: "192.168.10.2"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :debian do |debian|
  end

  config.vm.provision "shell", path: "provision/mongo.sh"

end