# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/debian-8.5"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "debian-8.5"
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.hostname = "debian"
  config.vm.network :private_network,
  	ip: "192.168.50.2",
  	virtualbox__intnet: "vagrant"




  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :debian do |debian|
  end

  config.vm.provision "shell", path: "provision/apt.sh"

## Database configuration

# uncomment to used mongodb
#  config.vm.provision "shell", path: "provision/mongo.sh"
#  config.vm.network "forwarded_port", guest: 27017 , host: 27017 , auto_correct: true

# uncomment to used mysql
#  config.vm.provision "shell", path: "provision/mysql.sh"
#  config.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct: true

# uncomment to used postgresql
  config.vm.provision "shell", path: "provision/postgresql.sh"
  config.vm.network "forwarded_port", guest: 5432 , host: 5432 , auto_correct: true

end